apiVersion: v1
kind: Service
metadata:
  name: accounts-api
  namespace: demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: project=brahma-demo
spec:
  type: LoadBalancer
  selector:
    app: accounts-api
  ports:
    - port: 80
      targetPort: 8000
